# Generated by Django 5.0.1 on 2024-01-25 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_customer_order_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
